"""
Utility functions for validation testing.

This module provides helper functions for:
- Loading atlas ROI data and centroids
- Mapping sources to ROIs
- Generating comprehensive validation reports with figures
- Creating publication-quality visualizations

Functions
---------
load_atlas_roi_centroids
    Extract ROI centroids from atlas NIfTI file
load_roi_source_mapping
    Map sources to ROIs using proximity-based search
get_roi_sources
    Get source indices belonging to an ROI
create_validation_report
    Generate comprehensive markdown report with figures

Examples
--------
>>> from source_localization.validation.utils import (
...     load_atlas_roi_centroids,
...     load_roi_source_mapping
... )
>>> # Load ROI centroids - use LABELS file (integer ROIs), not intensity file
>>> centroids, names = load_atlas_roi_centroids(
...     'Atlas_3DRoisLeftRight.Labels.nii',  # Integer ROI labels (1-46)
...     'roi_mapping.json'  # ROI names
... )
>>> print(f"Loaded {len(centroids)} ROIs")

>>> # Map sources to ROIs - also requires LABELS file
>>> roi_mapping = load_roi_source_mapping(
...     source_positions,
...     'Atlas_3DRoisLeftRight.Labels.nii'  # NOT Atlas_3DRois.nii
... )
>>> print(f"{np.sum(roi_mapping > 0)} sources mapped to ROIs")
"""

import numpy as np
import nibabel as nib
import json
from pathlib import Path
from typing import Dict, List, Tuple, Optional
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from datetime import datetime

__all__ = [
    'load_atlas_roi_centroids',
    'load_roi_source_mapping',
    'get_roi_sources',
    'create_validation_report',
    'generate_uniform_test_grid'
]


def corrected_atlas_affine(atlas_nii):
    """Return the voxel->mm affine for an atlas NIfTI, convention-aware.

    The pipeline's working space is the "10x" convention: atlas volumes are
    stored with voxel sizes ~10x too large (>1 mm; e.g. Atlas_3DRois.nii at
    ~2 mm) because FSL/ANTs behave better when the ~1 cm mouse brain is scaled
    to ~10 cm. get_true_affine (utils/atlas.py) and this pipeline divide by 10
    to recover true mm.

    However, some atlas LABEL files are instead stored already in true mm
    (~0.2 mm voxels; e.g. the Allen-32 allen_labels.nii.gz, re-saved at the
    2026-04 reg fix). Blindly dividing those by 10 double-corrects and
    collapses every coordinate to the brain center (~thalamus), silently
    breaking ROI-classification accuracy and uniform-grid generation.

    We therefore divide by 10 ONLY when the stored voxel size indicates the
    10x convention (>1 mm). Files already in true mm are used as-is. This keeps
    the source space, ROI centroids, and test grid in one consistent frame.
    """
    affine = atlas_nii.affine.copy()
    max_voxel_mm = float(np.abs(np.diag(affine)[:3]).max())
    if max_voxel_mm > 1.0:            # 10x (>1 mm) convention -> correct to true mm
        affine[:3, :3] /= 10.0
        affine[:3, 3] /= 10.0
    # else: already true mm -> use stored affine unchanged
    return affine


def generate_uniform_test_grid(
    roi_labels_nifti: str,
    spacing_mm: float = 1.0,
    margin_mm: float = 0.5,
    verbose: bool = True
) -> Tuple[np.ndarray, np.ndarray]:
    """
    Generate a uniform 3D grid of test positions within the brain volume.

    This provides position-independent validation by testing at fixed grid
    locations regardless of atlas parcellation. The grid spacing should be
    based on electrode array resolution (typically ~1.2 mm for mouse EEG).

    Parameters
    ----------
    roi_labels_nifti : str
        Path to NIfTI file containing INTEGER ROI labels.
        Used to determine brain boundaries.
        Example: "Atlas_3DRoisLeftRight.Labels.nii"
    spacing_mm : float, default=1.0
        Grid spacing in mm. Should match electrode resolution.
        Typical values: 1.0-1.2 mm for 30-channel mouse EEG arrays.
    margin_mm : float, default=0.5
        Inward margin from brain boundary to avoid edge effects.
        Points within this distance of the brain surface are excluded.
    verbose : bool, default=True
        Print grid statistics.

    Returns
    -------
    grid_positions_mm : ndarray, shape (n_points, 3)
        Uniform grid positions [x, y, z] in mm within the brain volume.
    grid_roi_labels : ndarray, shape (n_points,)
        ROI label for each grid point (for computing ROI accuracy separately).

    Notes
    -----
    The grid is generated by:
    1. Creating a regular 3D lattice covering the brain bounding box
    2. Filtering to points inside the brain mask (any ROI label > 0)
    3. Optionally applying an erosion margin to avoid boundary effects

    This ensures localization error is computed at consistent positions
    across different validation configurations, making the metric
    independent of atlas parcellation choice.

    Examples
    --------
    >>> grid_pos, grid_rois = generate_uniform_test_grid(
    ...     "Atlas_3DRoisLeftRight.Labels.nii",
    ...     spacing_mm=1.2  # Match electrode spacing
    ... )
    >>> print(f"Generated {len(grid_pos)} test positions")
    Generated 687 test positions

    >>> # Use in validation
    >>> for i, pos in enumerate(grid_pos):
    ...     eeg_data, meta = simulator.simulate_dipole(position_mm=pos)
    ...     # ... run inverse solution and compute error
    """
    from scipy.ndimage import distance_transform_edt

    # Load atlas
    atlas_nii = nib.load(roi_labels_nifti)
    atlas_data = atlas_nii.get_fdata().astype(int)

    # Validate that this is a labels file
    n_unique = len(np.unique(atlas_data))
    if n_unique > 200:
        raise ValueError(
            f"File '{roi_labels_nifti}' contains {n_unique} unique values. "
            f"Use a labels file (e.g., 'Atlas_3DRoisLeftRight.Labels.nii')."
        )

    # Convention-aware voxel->mm affine (only /10 the 10x-convention files)
    affine_corrected = corrected_atlas_affine(atlas_nii)

    # Create brain mask (any non-zero label)
    brain_mask = atlas_data > 0

    # Apply erosion margin using distance transform (handles anisotropic voxels properly)
    if margin_mm > 0:
        # Calculate voxel size from affine for distance transform
        voxel_size = np.abs(np.diag(affine_corrected)[:3])
        # Compute distance from boundary in mm using anisotropic voxel sizes
        distance_map = distance_transform_edt(brain_mask, sampling=voxel_size)
        brain_mask_eroded = distance_map >= margin_mm
    else:
        brain_mask_eroded = brain_mask

    # Get bounding box of eroded brain mask
    brain_voxels = np.argwhere(brain_mask_eroded)
    if len(brain_voxels) == 0:
        raise ValueError("No brain voxels found after erosion. Try smaller margin_mm.")

    min_voxel = brain_voxels.min(axis=0)
    max_voxel = brain_voxels.max(axis=0)

    # Convert bounding box to mm
    min_mm = nib.affines.apply_affine(affine_corrected, min_voxel)
    max_mm = nib.affines.apply_affine(affine_corrected, max_voxel)

    # Ensure min < max for each dimension
    for i in range(3):
        if min_mm[i] > max_mm[i]:
            min_mm[i], max_mm[i] = max_mm[i], min_mm[i]

    # Generate uniform grid
    x_coords = np.arange(min_mm[0], max_mm[0] + spacing_mm, spacing_mm)
    y_coords = np.arange(min_mm[1], max_mm[1] + spacing_mm, spacing_mm)
    z_coords = np.arange(min_mm[2], max_mm[2] + spacing_mm, spacing_mm)

    # Create meshgrid and flatten to list of 3D coordinates
    xx, yy, zz = np.meshgrid(x_coords, y_coords, z_coords, indexing='ij')
    grid_candidates = np.column_stack([xx.ravel(), yy.ravel(), zz.ravel()])

    if verbose:
        print(f"\n  Uniform test grid generation:")
        print(f"    Spacing: {spacing_mm} mm")
        print(f"    Margin: {margin_mm} mm")
        print(f"    Bounding box: [{min_mm[0]:.1f}, {max_mm[0]:.1f}] x "
              f"[{min_mm[1]:.1f}, {max_mm[1]:.1f}] x "
              f"[{min_mm[2]:.1f}, {max_mm[2]:.1f}] mm")
        print(f"    Initial grid candidates: {len(grid_candidates)}")

    # Filter to points inside the brain mask
    # Convert mm coordinates back to voxel indices
    affine_inv = np.linalg.inv(affine_corrected)
    grid_voxels = nib.affines.apply_affine(affine_inv, grid_candidates)
    grid_voxels_int = np.round(grid_voxels).astype(int)

    # Check bounds
    valid_mask = np.ones(len(grid_candidates), dtype=bool)
    for dim in range(3):
        valid_mask &= (grid_voxels_int[:, dim] >= 0)
        valid_mask &= (grid_voxels_int[:, dim] < atlas_data.shape[dim])

    # Check if inside eroded brain mask
    inside_brain = np.zeros(len(grid_candidates), dtype=bool)
    for i in range(len(grid_candidates)):
        if valid_mask[i]:
            vi, vj, vk = grid_voxels_int[i]
            inside_brain[i] = brain_mask_eroded[vi, vj, vk]

    # Filter to valid points
    grid_positions_mm = grid_candidates[inside_brain]

    # Get ROI labels for each grid point (for separate ROI accuracy calculation)
    grid_roi_labels = np.zeros(len(grid_positions_mm), dtype=int)
    grid_voxels_final = grid_voxels_int[inside_brain]
    for i, (vi, vj, vk) in enumerate(grid_voxels_final):
        grid_roi_labels[i] = atlas_data[vi, vj, vk]

    if verbose:
        unique_rois = np.unique(grid_roi_labels)
        print(f"    Points inside brain: {len(grid_positions_mm)}")
        print(f"    ROIs covered: {len(unique_rois[unique_rois > 0])}")
        print(f"    Grid points per ROI (mean): {len(grid_positions_mm) / len(unique_rois[unique_rois > 0]):.1f}")

    return grid_positions_mm, grid_roi_labels


def load_atlas_roi_centroids(
    roi_labels_nifti: str,
    roi_names_json: Optional[str] = None
) -> Tuple[Dict[int, np.ndarray], Dict[int, str]]:
    """
    Load ROI centroids from a NIfTI file containing integer ROI labels.

    IMPORTANT: This function expects a NIfTI file with INTEGER ROI labels (e.g., 1, 2, 3, ...),
    NOT a file with continuous intensity values. Using an intensity file will cause the function
    to hang as it tries to process millions of unique values.

    Correct file: Atlas_3DRoisLeftRight.Labels.nii (contains integers 1-46)
    Wrong file: Atlas_3DRois.nii (contains ~800,000 unique intensity values)

    Parameters
    ----------
    roi_labels_nifti : str
        Path to NIfTI file containing INTEGER ROI labels.
        Each voxel value should be an integer ROI ID (1, 2, 3, ...).
        Example: "Atlas_3DRoisLeftRight.Labels.nii"
    roi_names_json : str, optional
        Path to JSON file containing ROI names (e.g., roi_mapping.json).
        Expected format: {"rois": {"1": {"name": "Primary Motor"}, ...}}

    Returns
    -------
    roi_centroids : dict
        Mapping from ROI ID (int) to centroid position [x, y, z] in mm
    roi_names : dict
        Mapping from ROI ID (int) to ROI name (str)

    Raises
    ------
    ValueError
        If the NIfTI file contains too many unique values (likely intensity file)

    Examples
    --------
    >>> centroids, names = load_atlas_roi_centroids(
    ...     "data/atlas/Atlas_3DRoisLeftRight.Labels.nii",  # Integer labels
    ...     "data/atlas/roi_mapping.json"  # ROI names
    ... )
    """
    # Load atlas
    atlas_nii = nib.load(roi_labels_nifti)
    atlas_data = atlas_nii.get_fdata()
    affine = atlas_nii.affine.copy()

    # VALIDATION: Check that this is a labels file, not an intensity file
    unique_values = np.unique(atlas_data)
    n_unique = len(unique_values)
    n_nonzero = len(unique_values[unique_values > 0])

    if n_unique > 200:
        raise ValueError(
            f"File '{roi_labels_nifti}' contains {n_unique} unique values, "
            f"which suggests it's an INTENSITY file, not a LABELS file.\n"
            f"Expected: Integer ROI labels (e.g., 1-46 for ~47 unique values)\n"
            f"Use the labels file (e.g., 'Atlas_3DRoisLeftRight.Labels.nii') "
            f"instead of the intensity file (e.g., 'Atlas_3DRois.nii')."
        )

    # Check for integer-like values
    if not np.allclose(atlas_data, atlas_data.astype(int)):
        print(f"Warning: ROI labels file contains non-integer values. Rounding to nearest integer.")
        atlas_data = np.round(atlas_data).astype(int)

    # Convention-aware voxel->mm affine (only /10 the 10x-convention files).
    # Blindly dividing an already-true-mm label file (e.g. allen_labels.nii.gz)
    # collapses every ROI centroid to the brain center; see corrected_atlas_affine.
    affine = corrected_atlas_affine(atlas_nii)

    # Get unique ROI IDs
    roi_ids = np.unique(atlas_data)
    roi_ids = roi_ids[roi_ids > 0]  # Exclude background

    print(f"  Loading ROI centroids from {n_nonzero} ROIs...")

    roi_centroids = {}
    roi_names = {}

    outside = []
    for roi_id in roi_ids:
        # Get voxel coordinates for this ROI
        voxel_coords = np.array(np.where(atlas_data == roi_id)).T

        # Compute centroid in voxel space
        centroid_voxel = np.mean(voxel_coords, axis=0)

        # Convert to mm using corrected affine
        centroid_mm = nib.affines.apply_affine(affine, centroid_voxel)

        # WARNING: the geometric centroid of a NON-CONVEX parcel can fall
        # OUTSIDE the parcel. See module docstring of roi_test_points() and
        # load_atlas_roi_test_points() for the measured Allen-32 cases.
        ci = np.round(centroid_voxel).astype(int)
        in_bounds = all(0 <= ci[k] < atlas_data.shape[k] for k in range(3))
        if not in_bounds or int(atlas_data[tuple(ci)]) != int(roi_id):
            outside.append(int(roi_id))

        roi_centroids[int(roi_id)] = centroid_mm
        roi_names[int(roi_id)] = f"ROI_{int(roi_id)}"

    if outside:
        print(f"  NOTE: {len(outside)} ROI centroid(s) fall OUTSIDE their own ROI "
              f"(non-convex parcels): {sorted(outside)}.")
        print(f"        Scoring ROI classification at those points tests the wrong "
              f"label. Prefer load_atlas_roi_test_points(placement='medoid'|'sample').")

    # Load ROI names from JSON if provided
    if roi_names_json and Path(roi_names_json).exists():
        try:
            with open(roi_names_json, 'r') as f:
                names_data = json.load(f)
                # roi_mapping.json has format: {"rois": {"1": {"name": "...", ...}, ...}}
                if 'rois' in names_data:
                    for roi_id_str, label_info in names_data['rois'].items():
                        roi_id = int(roi_id_str)
                        if roi_id in roi_names:
                            roi_names[roi_id] = label_info.get('name', f"ROI_{roi_id}")
        except Exception as e:
            print(f"Warning: Could not load ROI names from JSON: {e}")

    print(f"  Loaded {len(roi_centroids)} ROI centroids")

    # Guard: ROI centroids must span a plausible mouse-brain extent (mm).
    # A tiny span means an affine/voxel-size convention mismatch collapsed every
    # ROI to the brain center (silently wrecking ROI-classification accuracy).
    # Fail loudly here instead of returning garbage.
    if len(roi_centroids) >= 2:
        span = np.ptp(np.array(list(roi_centroids.values())), axis=0)
        if float(span.max()) < 3.0:
            raise ValueError(
                f"ROI centroids span only {np.round(span, 2)} mm across "
                f"{len(roi_centroids)} ROIs — implausibly small for a mouse brain "
                f"(expected ~8-12 mm rostro-caudal). This indicates an atlas "
                f"voxel-size/affine convention mismatch for '{roi_labels_nifti}' "
                f"(e.g. a true-mm label file being divided by 10). "
                f"See corrected_atlas_affine()."
            )

    return roi_centroids, roi_names


def load_atlas_roi_test_points(
    roi_labels_nifti: str,
    roi_names_json: Optional[str] = None,
    placement: str = "medoid",
    n_per_roi: int = 1,
    seed: int = 20260728,
):
    """Generate ROI test points that are GUARANTEED to lie inside their own ROI.

    Replaces centroid placement for ROI-classification benchmarking.

    Why this exists
    ---------------
    The geometric centroid of a non-convex parcel can fall outside the parcel.
    Measured on Allen-32 (voxel size 0.203 x 0.080 x 0.200 mm), 5 of 32 centroids
    land outside their own ROI:

        Hippocampus_Post_L -> Thalamus_L       (0.23 mm from nearest in-ROI voxel)
        Hippocampus_Post_R -> Thalamus_R       (0.21 mm)
        Lateral_Cortex_L   -> unlabeled        (0.16 mm)
        Lateral_Cortex_R   -> unlabeled        (0.29 mm)
        Cerebellum_L       -> unlabeled        (0.09 mm)

    All five are thin curved sheets or C-shapes: bounding-box fill 10.6-22.5%
    versus 24-35% for convex parcels such as Somatosensory or Thalamus. The
    posterior hippocampus is a C wrapping the thalamus, so its centroid landing
    in thalamus is expected anatomy, not a parcellation defect -- every ROI is
    >=99.1% a single connected component.

    The displacement is only ~1 voxel, but it places the test dipole in a
    DIFFERENT structure while the trial is still scored against the original
    label. Consequences observed with centroid placement:
      * Lateral_Cortex_L/R scored recall 0.00 AND precision 0.00;
      * Hippocampus_Post_R trials were "misattributed" to Thalamus_R 16/25 times
        -- the inverse solution was right, the label was wrong.

    Parameters
    ----------
    placement : {"medoid", "sample", "centroid"}
        ``medoid``   nearest in-ROI voxel to the centroid. One point per ROI, so
                     it is directly comparable to legacy centroid results.
                     Verified inside its own ROI for all 32 Allen-32 parcels.
        ``sample``   ``n_per_roi`` voxels drawn within the ROI, spread by greedy
                     farthest-point selection from the medoid. A single point
                     cannot characterise a 5,000-voxel curved sheet; this gives
                     within-ROI coverage and variance.
        ``centroid`` legacy behaviour, retained only for reproducing historical
                     runs. Not recommended.
    n_per_roi : int
        Points per ROI; ignored unless ``placement="sample"``.
    seed : int
        Unused by the deterministic strategies; recorded for provenance.

    Returns
    -------
    test_points : dict[int, np.ndarray]
        ROI ID -> array of shape (n_points, 3) in mm.
    roi_names : dict[int, str]
    meta : dict
        ``placement``, ``n_per_roi``, ``seed``, and ``centroid_outside_roi``
        (the ROI IDs whose centroid was outside, i.e. what this fixes).
    """
    if placement not in ("medoid", "sample", "centroid"):
        raise ValueError(f"placement must be medoid|sample|centroid, got {placement!r}")

    atlas_nii = nib.load(roi_labels_nifti)
    atlas_data = np.round(atlas_nii.get_fdata()).astype(int)
    affine = corrected_atlas_affine(atlas_nii)

    _, roi_names = load_atlas_roi_centroids(roi_labels_nifti, roi_names_json)

    roi_ids = np.unique(atlas_data)
    roi_ids = roi_ids[roi_ids > 0]

    test_points = {}
    centroid_outside = []

    for roi_id in roi_ids:
        vox = np.array(np.where(atlas_data == roi_id)).T
        centroid_voxel = vox.mean(axis=0)

        ci = np.round(centroid_voxel).astype(int)
        in_bounds = all(0 <= ci[k] < atlas_data.shape[k] for k in range(3))
        if not in_bounds or int(atlas_data[tuple(ci)]) != int(roi_id):
            centroid_outside.append(int(roi_id))

        if placement == "centroid":
            chosen = centroid_voxel[None, :]
        else:
            d2c = np.linalg.norm(vox - centroid_voxel, axis=1)
            order = [int(np.argmin(d2c))]
            if placement == "sample" and n_per_roi > 1:
                # Greedy farthest-point: spread coverage over the parcel rather
                # than clustering near the (possibly exterior) centroid.
                mind = np.linalg.norm(vox - vox[order[0]], axis=1)
                for _ in range(min(n_per_roi, len(vox)) - 1):
                    nxt = int(np.argmax(mind))
                    order.append(nxt)
                    mind = np.minimum(mind, np.linalg.norm(vox - vox[nxt], axis=1))
            chosen = vox[order].astype(float)

        pts = nib.affines.apply_affine(affine, chosen)

        # Hard guarantee: every returned point must be inside its own ROI.
        if placement != "centroid":
            for p in np.atleast_2d(pts):
                vi = np.round(nib.affines.apply_affine(
                    np.linalg.inv(affine), p)).astype(int)
                ok = all(0 <= vi[k] < atlas_data.shape[k] for k in range(3))
                if not ok or int(atlas_data[tuple(vi)]) != int(roi_id):
                    raise AssertionError(
                        f"placement={placement!r} produced a point outside ROI "
                        f"{roi_id} ({roi_names.get(int(roi_id))}). This is the "
                        f"exact failure mode this function exists to prevent."
                    )

        test_points[int(roi_id)] = np.atleast_2d(pts)

    meta = {"placement": placement, "n_per_roi": n_per_roi, "seed": seed,
            "centroid_outside_roi": sorted(centroid_outside),
            "n_centroid_outside": len(centroid_outside)}

    print(f"  ROI test points: placement={placement}, "
          f"{sum(len(v) for v in test_points.values())} points across "
          f"{len(test_points)} ROIs")
    if centroid_outside:
        print(f"    (legacy centroid placement would have put {len(centroid_outside)} "
              f"ROI(s) outside their own parcel: {sorted(centroid_outside)})")

    return test_points, roi_names, meta


def load_roi_source_mapping(
    source_positions_mm: np.ndarray,
    roi_labels_nifti: str,
    verbose: bool = False,
    radius_mm: float = 1.0,
    scale_factor: float = 1.0
) -> np.ndarray:
    """
    Map each source to its corresponding ROI using proximity-based search.

    Uses the same proximity-based mapping as the pipelines (KD-tree search
    within radius_mm of atlas voxels) for consistency and robustness.

    IMPORTANT: This function expects a NIfTI file with INTEGER ROI labels,
    NOT a file with continuous intensity values.

    For brain_size validation tests with scale_factor > 1.0, the source
    positions are scaled up while the atlas remains at mouse scale. We scale
    the atlas voxel coordinates to match the source positions.

    Parameters
    ----------
    source_positions_mm : ndarray, shape (n_sources, 3)
        Source positions in mm
    roi_labels_nifti : str
        Path to NIfTI file containing INTEGER ROI labels.
        Example: "Atlas_3DRoisLeftRight.Labels.nii" (NOT Atlas_3DRois.nii)
    verbose : bool
        Print debugging information
    radius_mm : float
        Proximity search radius in mm (default: 1.0)
    scale_factor : float
        Scale factor for brain_size tests (default: 1.0).
        When > 1.0, atlas voxel coordinates are scaled to match source positions.

    Returns
    -------
    roi_mapping : ndarray, shape (n_sources,)
        ROI ID for each source (0 = no ROI assignment, or primary ROI if multiple)

    Raises
    ------
    ValueError
        If the NIfTI file contains too many unique values (likely intensity file)
    """
    from scipy.spatial import cKDTree

    # Load atlas
    atlas_nii = nib.load(roi_labels_nifti)
    atlas_data = atlas_nii.get_fdata()

    # VALIDATION: Check that this is a labels file, not an intensity file
    n_unique = len(np.unique(atlas_data))
    if n_unique > 200:
        raise ValueError(
            f"File '{roi_labels_nifti}' contains {n_unique} unique values, "
            f"which suggests it's an INTENSITY file, not a LABELS file.\n"
            f"Use the labels file (e.g., 'Atlas_3DRoisLeftRight.Labels.nii')."
        )

    atlas_data = atlas_data.astype(int)

    if verbose:
        print(f"\n=== ROI Mapping Debug (Proximity-Based) ===")
        print(f"ROI labels file: {roi_labels_nifti}")
        print(f"Atlas data shape: {atlas_data.shape}")
        print(f"Atlas unique values: {len(np.unique(atlas_data))} total")
        print(f"Radius: {radius_mm} mm")
        print(f"Source positions shape: {source_positions_mm.shape}")
        print(f"Source position range (mm):")
        print(f"  X: [{source_positions_mm[:, 0].min():.2f}, {source_positions_mm[:, 0].max():.2f}]")
        print(f"  Y: [{source_positions_mm[:, 1].min():.2f}, {source_positions_mm[:, 1].max():.2f}]")
        print(f"  Z: [{source_positions_mm[:, 2].min():.2f}, {source_positions_mm[:, 2].max():.2f}]")

    # Get all non-zero voxel coordinates and their labels
    roi_voxels = np.argwhere(atlas_data > 0)  # (n_roi_voxels, 3)
    roi_labels_flat = atlas_data[roi_voxels[:, 0], roi_voxels[:, 1], roi_voxels[:, 2]]

    if verbose:
        print(f"ROI voxels found: {len(roi_voxels)}")
        print(f"Unique ROI labels: {len(np.unique(roi_labels_flat))}")

    # Convention-aware voxel->mm affine (only /10 the 10x-convention files)
    affine_corrected = corrected_atlas_affine(atlas_nii)

    roi_voxels_mm = nib.affines.apply_affine(affine_corrected, roi_voxels)

    # Apply scale factor for brain_size tests
    if scale_factor != 1.0:
        roi_voxels_mm = roi_voxels_mm * scale_factor
        if verbose:
            print(f"Applied {scale_factor}x scale factor to atlas voxel coordinates")

    if verbose:
        print(f"ROI voxel range (mm):")
        print(f"  X: [{roi_voxels_mm[:, 0].min():.2f}, {roi_voxels_mm[:, 0].max():.2f}]")
        print(f"  Y: [{roi_voxels_mm[:, 1].min():.2f}, {roi_voxels_mm[:, 1].max():.2f}]")
        print(f"  Z: [{roi_voxels_mm[:, 2].min():.2f}, {roi_voxels_mm[:, 2].max():.2f}]")

    # Build KD-tree for efficient proximity search
    tree = cKDTree(roi_voxels_mm)

    # For each source, find closest ROI voxel within radius
    n_sources = source_positions_mm.shape[0]
    roi_mapping = np.zeros(n_sources, dtype=int)
    n_mapped = 0

    for i, src_coord in enumerate(source_positions_mm):
        # Find all voxels within radius
        indices = tree.query_ball_point(src_coord, radius_mm)

        if len(indices) > 0:
            # Get ROI labels for nearby voxels
            nearby_rois = roi_labels_flat[indices]
            unique_rois, counts = np.unique(nearby_rois, return_counts=True)

            # Assign most frequent ROI (in case of overlap)
            roi_mapping[i] = unique_rois[np.argmax(counts)]
            n_mapped += 1

        # Print first few mappings for debugging
        if verbose and i < 5:
            print(f"  Source {i}: {src_coord} mm → ROI {roi_mapping[i]} ({len(indices)} nearby voxels)")

    if verbose:
        unique_rois = np.unique(roi_mapping[roi_mapping > 0])
        print(f"\nMapping Results:")
        print(f"  Sources mapped to ROIs: {n_mapped}/{n_sources} ({100*n_mapped/n_sources:.1f}%)")
        print(f"  Sources unmapped: {n_sources - n_mapped}")
        print(f"  Unique ROIs found: {len(unique_rois)}")
        print(f"  ROI IDs: {sorted(unique_rois)}")
        print(f"======================\n")

    return roi_mapping


def get_roi_sources(
    roi_id: int,
    roi_mapping: np.ndarray
) -> np.ndarray:
    """
    Get indices of sources belonging to an ROI.

    Parameters
    ----------
    roi_id : int
        ROI identifier
    roi_mapping : ndarray, shape (n_sources,)
        ROI assignment for each source

    Returns
    -------
    roi_sources : ndarray
        Indices of sources in the ROI
    """
    return np.where(roi_mapping == roi_id)[0]


def create_validation_report(
    results: List[Dict],
    pipeline_name: str,
    output_dir: str,
    roi_names: Optional[Dict[int, str]] = None
) -> str:
    """
    Generate comprehensive validation report with figures.

    Parameters
    ----------
    results : list of dict
        Validation results for each test
    pipeline_name : str
        Name of the pipeline being validated
    output_dir : str
        Directory to save report and figures
    roi_names : dict, optional
        ROI ID to name mapping

    Returns
    -------
    report_path : str
        Path to generated markdown report
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Generate figures
    figures_dir = output_dir / 'figures'
    figures_dir.mkdir(exist_ok=True)

    fig_paths = _create_validation_figures(
        results, pipeline_name, figures_dir, roi_names
    )

    # Generate markdown report
    report_path = output_dir / f'{pipeline_name}_validation_report.md'

    with open(report_path, 'w') as f:
        # Header
        f.write(f"# Validation Report: {pipeline_name}\n\n")
        f.write(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        f.write(f"**Number of tests:** {len(results)}\n\n")
        f.write("---\n\n")

        # Summary statistics
        f.write("## Summary Statistics\n\n")
        f.write(_format_summary_table(results))
        f.write("\n\n")

        # Figures
        f.write("## Validation Figures\n\n")
        for fig_name, fig_path in fig_paths.items():
            rel_path = fig_path.relative_to(output_dir)
            f.write(f"### {fig_name}\n\n")
            f.write(f"![{fig_name}]({rel_path})\n\n")

        # Per-ROI results
        f.write("## Per-ROI Results\n\n")
        f.write(_format_roi_results_table(results, roi_names))

    return str(report_path)


def _create_validation_figures(
    results: List[Dict],
    pipeline_name: str,
    figures_dir: Path,
    roi_names: Optional[Dict] = None
) -> Dict[str, Path]:
    """Create validation figures and return paths."""
    fig_paths = {}

    # Figure 1: Localization Error Distribution
    fig_path = figures_dir / f'{pipeline_name}_localization_error.png'
    _plot_localization_error_distribution(results, fig_path, pipeline_name)
    fig_paths['Localization Error Distribution'] = fig_path

    # Figure 2: ROI Classification Accuracy
    fig_path = figures_dir / f'{pipeline_name}_roi_accuracy.png'
    _plot_roi_accuracy(results, fig_path, pipeline_name, roi_names)
    fig_paths['ROI Classification Accuracy'] = fig_path

    # Figure 3: PSF Analysis
    fig_path = figures_dir / f'{pipeline_name}_psf_analysis.png'
    _plot_psf_analysis(results, fig_path, pipeline_name)
    fig_paths['Point Spread Function Analysis'] = fig_path

    # Figure 4: Error vs Depth
    if any('true_position_mm' in r for r in results):
        fig_path = figures_dir / f'{pipeline_name}_error_vs_depth.png'
        _plot_error_vs_depth(results, fig_path, pipeline_name)
        fig_paths['Localization Error vs Depth'] = fig_path

    return fig_paths


def _plot_localization_error_distribution(results, fig_path, pipeline_name):
    """Plot histogram and boxplot of localization errors."""
    errors = [r['localization_error_mm'] for r in results if 'localization_error_mm' in r]

    if not errors:
        return

    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    # Histogram
    axes[0].hist(errors, bins=20, edgecolor='black', alpha=0.7)
    axes[0].axvline(np.mean(errors), color='red', linestyle='--', label=f'Mean: {np.mean(errors):.2f} mm')
    axes[0].axvline(np.median(errors), color='orange', linestyle='--', label=f'Median: {np.median(errors):.2f} mm')
    axes[0].set_xlabel('Localization Error (mm)')
    axes[0].set_ylabel('Count')
    axes[0].set_title(f'{pipeline_name}\nLocalization Error Distribution')
    axes[0].legend()
    axes[0].grid(True, alpha=0.3)

    # Boxplot
    axes[1].boxplot(errors, vert=True)
    axes[1].set_ylabel('Localization Error (mm)')
    axes[1].set_title(f'{pipeline_name}\nError Distribution (Boxplot)')
    axes[1].grid(True, alpha=0.3, axis='y')

    # Add percentile markers
    p95 = np.percentile(errors, 95)
    axes[1].axhline(p95, color='red', linestyle=':', label=f'95th percentile: {p95:.2f} mm')
    axes[1].legend()

    plt.tight_layout()
    plt.savefig(fig_path, dpi=300, bbox_inches='tight')
    plt.close()


def _plot_roi_accuracy(results, fig_path, pipeline_name, roi_names):
    """Plot ROI classification accuracy."""
    # Aggregate results by ROI
    roi_results = {}
    for r in results:
        if 'true_roi' in r and 'roi_correct' in r:
            roi_id = r['true_roi']
            if roi_id not in roi_results:
                roi_results[roi_id] = {'correct': 0, 'incorrect': 0}

            if r['roi_correct']:
                roi_results[roi_id]['correct'] += 1
            else:
                roi_results[roi_id]['incorrect'] += 1

    if not roi_results:
        return

    # Calculate accuracy per ROI
    roi_ids = sorted(roi_results.keys())
    accuracies = [
        roi_results[roi_id]['correct'] / (roi_results[roi_id]['correct'] + roi_results[roi_id]['incorrect'])
        for roi_id in roi_ids
    ]

    fig, ax = plt.subplots(figsize=(14, 6))

    # Bar plot
    bars = ax.bar(range(len(roi_ids)), accuracies, edgecolor='black')

    # Color bars (green if accuracy >= 0.9, yellow if >= 0.7, red otherwise)
    for i, acc in enumerate(accuracies):
        if acc >= 0.9:
            bars[i].set_color('green')
            bars[i].set_alpha(0.7)
        elif acc >= 0.7:
            bars[i].set_color('orange')
            bars[i].set_alpha(0.7)
        else:
            bars[i].set_color('red')
            bars[i].set_alpha(0.7)

    # Labels
    if roi_names:
        labels = [roi_names.get(roi_id, f"ROI{roi_id}") for roi_id in roi_ids]
    else:
        labels = [f"ROI{roi_id}" for roi_id in roi_ids]

    ax.set_xticks(range(len(roi_ids)))
    ax.set_xticklabels(labels, rotation=90, ha='right')
    ax.set_ylabel('Classification Accuracy')
    ax.set_title(f'{pipeline_name}\nROI Classification Accuracy')
    ax.axhline(0.9, color='green', linestyle='--', label='90% threshold', alpha=0.5)
    ax.axhline(np.mean(accuracies), color='blue', linestyle='--', label=f'Mean: {np.mean(accuracies):.2%}')
    ax.set_ylim([0, 1.05])
    ax.legend()
    ax.grid(True, alpha=0.3, axis='y')

    plt.tight_layout()
    plt.savefig(fig_path, dpi=300, bbox_inches='tight')
    plt.close()


def _plot_psf_analysis(results, fig_path, pipeline_name):
    """Plot point spread function metrics."""
    fwhm_values = []
    n_active_values = []

    for r in results:
        if 'psf_metrics' in r:
            fwhm_values.append(r['psf_metrics']['fwhm_mm'])
            n_active_values.append(r['psf_metrics']['n_sources_active'])

    if not fwhm_values:
        return

    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    # FWHM distribution
    axes[0].hist(fwhm_values, bins=20, edgecolor='black', alpha=0.7)
    axes[0].axvline(np.mean(fwhm_values), color='red', linestyle='--',
                   label=f'Mean: {np.mean(fwhm_values):.2f} mm')
    axes[0].set_xlabel('FWHM (mm)')
    axes[0].set_ylabel('Count')
    axes[0].set_title(f'{pipeline_name}\nPoint Spread Function Width')
    axes[0].legend()
    axes[0].grid(True, alpha=0.3)

    # Number of active sources
    axes[1].hist(n_active_values, bins=20, edgecolor='black', alpha=0.7)
    axes[1].axvline(np.mean(n_active_values), color='red', linestyle='--',
                   label=f'Mean: {np.mean(n_active_values):.1f}')
    axes[1].set_xlabel('Number of Active Sources (>50% of peak)')
    axes[1].set_ylabel('Count')
    axes[1].set_title(f'{pipeline_name}\nSource Spread')
    axes[1].legend()
    axes[1].grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(fig_path, dpi=300, bbox_inches='tight')
    plt.close()


def _plot_error_vs_depth(results, fig_path, pipeline_name):
    """
    Plot localization error vs source depth with binned statistics.

    Creates a 2-panel figure:
    - Left: Scatter plot with regression line
    - Right: Box plot by depth bin showing error distribution
    """
    depths = []
    errors = []
    z_coords = []

    for r in results:
        if 'true_position_mm' in r and 'localization_error_mm' in r:
            z_coords.append(r['true_position_mm'][2])
            errors.append(r['localization_error_mm'])

    if not z_coords:
        return

    # Calculate depth from brain surface (top Z - position Z)
    brain_top_z = max(z_coords)
    depths = [brain_top_z - z for z in z_coords]

    fig, axes = plt.subplots(1, 2, figsize=(14, 6))

    # Left panel: Scatter plot with trend line
    ax1 = axes[0]
    scatter = ax1.scatter(depths, errors, alpha=0.4, s=30, c=errors,
                          cmap='RdYlGn_r', vmin=0, vmax=max(5, np.percentile(errors, 95)))

    # Trend line
    if len(depths) > 1:
        z = np.polyfit(depths, errors, 1)
        p = np.poly1d(z)
        x_trend = np.linspace(min(depths), max(depths), 100)
        ax1.plot(x_trend, p(x_trend), 'k--', linewidth=2, alpha=0.8,
                label=f'Slope: {z[0]:.2f} mm/mm depth')

        # Calculate correlation
        corr = np.corrcoef(depths, errors)[0, 1]
        ax1.text(0.05, 0.95, f'r = {corr:.3f}', transform=ax1.transAxes,
                fontsize=11, verticalalignment='top',
                bbox=dict(boxstyle='round', facecolor='white', alpha=0.8))

    ax1.set_xlabel('Depth from Brain Surface (mm)', fontsize=12)
    ax1.set_ylabel('Localization Error (mm)', fontsize=12)
    ax1.set_title(f'{pipeline_name}\nLocalization Error vs Depth', fontsize=13)
    ax1.legend(loc='lower right')
    ax1.grid(True, alpha=0.3)
    plt.colorbar(scatter, ax=ax1, label='Error (mm)')

    # Right panel: Box plot by depth bin
    ax2 = axes[1]
    depth_bins = [(0, 1, '0-1'), (1, 2, '1-2'), (2, 3, '2-3'), (3, 4, '3-4'), (4, float('inf'), '4+')]
    bin_data = []
    bin_labels = []
    bin_counts = []

    for low, high, label in depth_bins:
        bin_errors = [e for d, e in zip(depths, errors) if low <= d < high]
        if bin_errors:
            bin_data.append(bin_errors)
            bin_labels.append(f'{label}\n(n={len(bin_errors)})')
            bin_counts.append(len(bin_errors))
        else:
            bin_data.append([])
            bin_labels.append(f'{label}\n(n=0)')
            bin_counts.append(0)

    # Box plot
    bp = ax2.boxplot([b for b in bin_data if b], labels=[l for l, b in zip(bin_labels, bin_data) if b],
                     patch_artist=True)

    # Color boxes by mean error
    colors = plt.cm.RdYlGn_r(np.linspace(0.2, 0.8, len([b for b in bin_data if b])))
    for patch, color in zip(bp['boxes'], colors):
        patch.set_facecolor(color)
        patch.set_alpha(0.7)

    # Add mean markers
    means = [np.mean(b) for b in bin_data if b]
    positions = range(1, len(means) + 1)
    ax2.scatter(positions, means, color='black', marker='D', s=50, zorder=5, label='Mean')

    ax2.set_xlabel('Depth Bin (mm)', fontsize=12)
    ax2.set_ylabel('Localization Error (mm)', fontsize=12)
    ax2.set_title(f'{pipeline_name}\nError Distribution by Depth', fontsize=13)
    ax2.legend(loc='upper left')
    ax2.grid(True, alpha=0.3, axis='y')

    # Add summary statistics text
    overall_mean = np.mean(errors)
    overall_std = np.std(errors)
    ax2.text(0.98, 0.98, f'Overall: {overall_mean:.2f} ± {overall_std:.2f} mm',
            transform=ax2.transAxes, fontsize=10, verticalalignment='top',
            horizontalalignment='right',
            bbox=dict(boxstyle='round', facecolor='white', alpha=0.8))

    plt.tight_layout()
    plt.savefig(fig_path, dpi=300, bbox_inches='tight')
    plt.close()


def _format_summary_table(results):
    """Format summary statistics as markdown table."""
    from source_localization.validation.metrics import summarize_validation_results

    summary = summarize_validation_results(results)

    table = "| Metric | Value |\n|--------|-------|\n"
    table += f"| **Localization Error** | |\n"
    table += f"| Mean | {summary['localization_error']['mean_mm']:.3f} mm |\n"
    table += f"| Median | {summary['localization_error']['median_mm']:.3f} mm |\n"
    table += f"| Std Dev | {summary['localization_error']['std_mm']:.3f} mm |\n"
    table += f"| 95th Percentile | {summary['localization_error']['percentile_95']:.3f} mm |\n"
    table += f"| **ROI Classification** | |\n"
    table += f"| Accuracy | {summary['roi_classification']['accuracy']:.1%} |\n"
    table += f"| Correct | {summary['roi_classification']['n_correct']} |\n"
    table += f"| Incorrect | {summary['roi_classification']['n_incorrect']} |\n"
    table += f"| **Point Spread Function** | |\n"
    table += f"| Mean FWHM | {summary['psf']['mean_fwhm_mm']:.3f} mm |\n"

    return table


def _format_roi_results_table(results, roi_names):
    """Format per-ROI results as markdown table."""
    # Group by ROI
    roi_data = {}
    for r in results:
        if 'true_roi' in r:
            roi_id = r['true_roi']
            if roi_id not in roi_data:
                roi_data[roi_id] = {
                    'errors': [],
                    'correct': 0,
                    'total': 0
                }

            roi_data[roi_id]['errors'].append(r.get('localization_error_mm', np.nan))
            roi_data[roi_id]['total'] += 1
            if r.get('roi_correct', False):
                roi_data[roi_id]['correct'] += 1

    # Build table
    table = "| ROI ID | ROI Name | Mean Error (mm) | Accuracy | Tests |\n"
    table += "|--------|----------|-----------------|----------|-------|\n"

    for roi_id in sorted(roi_data.keys()):
        data = roi_data[roi_id]
        name = roi_names.get(roi_id, f"ROI_{roi_id}") if roi_names else f"ROI_{roi_id}"
        mean_error = np.nanmean(data['errors'])
        accuracy = data['correct'] / data['total'] if data['total'] > 0 else 0.0

        table += f"| {roi_id} | {name} | {mean_error:.3f} | {accuracy:.1%} | {data['total']} |\n"

    return table
